### ISSUE TITLE
Create cached data sources & API endpoint

### ISSUE THREAD

**Issue by bnvk** [TheTorProject/ooni-explorer#32]
The following data needs to exist in order to better flesh out the some of the new interface ideas and improvements. This is a master ticket of the following data sources:

- [x] ASN
- [ ] Alexa rankings
- [ ] # of Google results for "www.domainname.com"
- [x] Categories for domain names

**Comment by hellais** [comment]
I have added support for these two fields and the production DB has it.

There is also support for extracting the other two items, but google and alexa end up blocking me after a menial number of requests. In order to do this properly it's going to require quite a bit of work, so I am going to defer this for the moment to something after the first release.

**Comment by simonv3** [comment]
Yeah, I got that far with Alexa as well, I'm happy with it being deferred.

**Comment by hellais** [comment]
For the beta release we can consider this closed. I will create a separate ticket for improvements that include:

*  Alexa rankings
*  # of Google results for "www.domainname.com"
