### ISSUE TITLE
Refactor "Measurement" page

### ISSUE THREAD

**Issue by bnvk** [TheTorProject/ooni-explorer#35]
A bunch of ideas and random, lil doo-dads to the improve this here tentacle octopus! The biggest thing is the first item- is re-jiggering this underneath the country page!

- [x] Move entire page as a sub page of "Country" page
- [x] Rename "report" to "measurement"
- [x] Pull in ASN data
- [x] Minimize and make measurement ID less important
- [x] Add category (tampering, blocking)
- [x] Structure better with Date, Test Type, Details, and Description
- [x] Change "What does this test do?" to "HTTTP Request"

...revist one these are done...

**Comment by hellais** [comment]
We should perhaps consider adding to this list of UI improvements the removal of the probe_ip address from the top bar or at least making it less visible as in most cases it's set to localhost (since users don't wish to submit their IP to us) and even when we do have it it's not of great value or interest to users.
