### ISSUE TITLE
Uganda page not loading

### ISSUE THREAD

**Issue by jmatsushita** [TheTorProject/ooni-explorer#38]
The page remains in loading mode and following error is in the JS console:

```
map clicked 1455790748
scripts.js:1 country controller loaded 1455790749
http://explorer.ooni.io/bower_components/factbook-country-data/data/UG.json Failed to load resource: the server responded with a status of 404 (Not Found)
scripts.js:1 error Objectconfig: Objectdata: Objectheaders: (c)status: 404statusText: "Not Found"__proto__: Object
```

I guess that failing to load the factbook file shouldn't prevent loading of the data.

Cheers!

Jun

**Comment by jmatsushita** [comment]
It seems that the loading just took a long time but eventually worked. So it might be a usability bug rather than a technical bug. Progress bar?

**Comment by simonv3** [comment]
Hey @jmatsushita, the server can take a pretty long time to display the information. UG not existing is probably a different problem. 

I'll have to dig a bit deeper on the UG front, since a quick check at it's existence in the bower install says it's there: https://github.com/simonv3/factbook-country-data/blob/master/data/ug.json

**Comment by hellais** [comment]
I think this can be closed. We have in the meantime also done some DB improvements that have made the response time much better.
