### ISSUE TITLE
API Endpoints Design

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-explorer#7]
Started a page for this: https://github.com/TheTorProject/ooni-api/wiki/API-Design

We can use this ticket to sketch out initial ideas.

**Comment by TylerJFisher** [comment]
Updated: https://github.com/TheTorProject/ooni-api/wiki/API-Design

**Comment by hellais** [comment]
Very good job on the API specification.

Just to be clear that I understand some things about it.

Your suggestion is to place all the test specific keys inside of the `test_keys` value (using the JSON feature of PostgreSQL) of the `Metrics` table and to generate some test specific views (that assess what Metrics present anomalies) based on some PgSQL procedures that get run in batch.
Is this accurate?

**Comment by TylerJFisher** [comment]
Thanks, @hellais! That's correct - in order to implement this I'd likely opt to use a trigger within either PostgreSQL, or within middleware somewhere (e.g. ooni-pipeline using an ORM framework). The goal behind explicitly separating _common_ and _test-specific_ keys is to allow for test-specific tables, and views to be created.

**Comment by hellais** [comment]
Issue moved to [TheTorProject/ooni-measurements #8](https://github.com/TheTorProject/ooni-measurements/issues/8) via [**ZenHub**](https://www.zenhub.com/)
